### ISSUE TITLE
BDFL says you should use list comprehension instead of filter

### ISSUE THREAD

**Issue by MaciekPytel** [vevurka/dungeons#2]
https://github.com/vevurka/dungeons/blob/master/dungeon.py#L260

For reference check third paragraph of Guido's article http://www.artima.com/weblogs/viewpost.jsp?thread=98196

> I think dropping filter() and map() is pretty uncontroversial; filter(P, S) is almost always written clearer as [x for x in S if P(x)]

**Comment by vevurka** [comment]
Fixed :)
